"""
GraphRAG Service
================
Wrapper around Microsoft GraphRAG 0.3.6.

Responsibilities:
  - Prepare a per-document working directory with settings.yaml
  - Run the GraphRAG indexing pipeline as a subprocess
  - Parse parquet output into typed Python dataclasses
  - Build and run GlobalSearch (Discover mode)
  - Build and run LocalSearch (Connect / Challenge mode)

What this file does NOT do:
  - Write to Neo4j  → caller (Lambda handler) does that
  - Know about HTTP  → routers handle that
  - Load .env        → config.py handles that

Design decisions:
  - Per-document working directories   → safe for concurrent Lambda runs
  - Subprocess for indexing            → stable API; GraphRAG CLI is the
                                         intended entry point for indexing
  - GraphRAG Python API for querying   → gives typed SearchResult objects
                                         with richer metadata than CLI output
  - Singleton via module-level instance → one object shared across the app
"""

from __future__ import annotations

import asyncio
import logging
import shutil
import subprocess
import tempfile
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import pandas as pd
import tiktoken

from graphrag.query.context_builder.entity_extraction import EntityVectorStoreKey
from graphrag.query.indexer_adapters import (
    read_indexer_entities,
    read_indexer_relationships,
    read_indexer_reports,
    read_indexer_text_units,
)
from graphrag.query.llm.oai.chat_openai import ChatOpenAI
from graphrag.query.llm.oai.embedding import OpenAIEmbedding
from graphrag.query.llm.oai.typing import OpenaiApiType
from graphrag.query.structured_search.global_search.community_context import (
    GlobalCommunityContext,
)
from graphrag.query.structured_search.global_search.search import GlobalSearch
from graphrag.query.structured_search.local_search.mixed_context import (
    LocalSearchMixedContext,
)
from graphrag.query.structured_search.local_search.search import LocalSearch
from graphrag.vector_stores.lancedb import LanceDBVectorStore

from config import get_settings

logger = logging.getLogger(__name__)

# ── NVIDIA NIM endpoint (OpenAI-compatible) ──────────────────────────────────
# NIM exposes the same REST surface as OpenAI, so GraphRAG's ChatOpenAI client
# works by pointing api_base at NIM and setting api_type to OpenAI.
NVIDIA_NIM_BASE_URL = "https://integrate.api.nvidia.com/v1"
NVIDIA_NIM_MODEL    = "meta/llama-3.1-8b-instruct"

# NIM does not expose an embeddings endpoint (as of 0.3.6 integration).
# We use a lightweight OpenAI-compatible embedding via NIM's nvolveqa model.
NVIDIA_EMBED_MODEL  = "nvidia/nv-embedqa-e5-v5"

# GraphRAG community detection level — 0 is the coarsest (fastest), 1 is finer.
# Level 2 is available but slow for free-tier NIM.
COMMUNITY_LEVEL = 1


# ── Typed return types ────────────────────────────────────────────────────────

@dataclass
class ExtractedEntity:
    """One entity extracted from a document."""
    id:          str
    name:        str
    type:        str
    description: str
    community:   str | None = None  # community id this entity belongs to


@dataclass
class ExtractedRelationship:
    """One directional relationship between two entities."""
    id:          str
    source:      str   # entity name
    target:      str   # entity name
    type:        str
    description: str
    weight:      float = 1.0


@dataclass
class ExtractedCommunity:
    """One community (cluster of related entities) with its LLM summary."""
    id:      str
    title:   str
    summary: str
    level:   int


@dataclass
class IndexingResult:
    """
    Everything produced by run_indexing().
    The Lambda handler receives this and saves each list to Neo4j.
    """
    doc_id:         str
    entities:       list[ExtractedEntity]       = field(default_factory=list)
    relationships:  list[ExtractedRelationship] = field(default_factory=list)
    communities:    list[ExtractedCommunity]    = field(default_factory=list)


@dataclass
class SearchResult:
    """Returned by global_search() and local_search()."""
    response:       str
    entities_used:  list[str]   = field(default_factory=list)  # entity names touched
    completion_time: float      = 0.0
    llm_calls:      int         = 0
    prompt_tokens:  int         = 0


# ── settings.yaml template ────────────────────────────────────────────────────
# GraphRAG requires a settings.yaml in the working directory.
# We generate one per-document so that each doc gets its own isolated run.
# Only the fields GraphRAG actually needs are included — unused features
# (async_mode, cache, snapshots) are left at defaults.

_SETTINGS_TEMPLATE = """\
# Auto-generated by graphrag_service.py — do not edit manually.
encoding_model: cl100k_base
skip_workflows: []

llm:
  api_key: {api_key}
  type: openai_chat
  model: {model}
  model_supports_json: true
  max_tokens: 2048
  temperature: 0
  api_base: {api_base}

parallelization:
  stagger: 0.3
  num_threads: 4

async_mode: threaded

embeddings:
  async_mode: threaded
  llm:
    api_key: {api_key}
    type: openai_embedding
    model: {embed_model}
    api_base: {api_base}

chunks:
  size: 300
  overlap: 100
  group_by_columns: [id]

input:
  type: file
  file_type: text
  base_dir: input

cache:
  type: file
  base_dir: cache

storage:
  type: file
  base_dir: output

reporting:
  type: file
  base_dir: logs

entity_extraction:
  prompt: prompts/entity_extraction.txt
  entity_types: [organization, person, concept, location, technology, event]
  max_gleanings: 1

summarize_descriptions:
  prompt: prompts/summarize_descriptions.txt
  max_length: 500

claim_extraction:
  enabled: false

community_reports:
  prompt: prompts/community_report.txt
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false

umap:
  enabled: false

snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false

local_search:
  text_unit_prop: 0.5
  community_prop: 0.1
  conversation_history_max_turns: 5
  top_k_entities: 10
  top_k_relationships: 10
  max_tokens: 12000

global_search:
  max_tokens: 12000
  data_max_tokens: 12000
  map_max_tokens: 1000
  reduce_max_tokens: 2000
  concurrency: 32
"""


# ── GraphRAGService ───────────────────────────────────────────────────────────

class GraphRAGService:
    """
    Singleton service for all GraphRAG operations.

    Usage (from Lambda handler):
        result: IndexingResult = await graphrag_service.run_indexing(doc_id, text)
        # then save result.entities, result.relationships, result.communities to Neo4j

    Usage (from query router):
        result: SearchResult = await graphrag_service.global_search(query)
        result: SearchResult = await graphrag_service.local_search(query, entity_names)
    """

    def __init__(self) -> None:
        self._settings = get_settings()
        # Base working directory — contains the global LanceDB vector store
        # that is shared across queries (but NOT across indexing runs).
        self._base_workdir = Path(self._settings.graphrag_workdir)
        self._vector_store_dir = self._base_workdir / "vector_store"

        # Lazy-loaded query objects — built once on first query call.
        # Rebuilding is expensive (loads all parquet files), so we cache them.
        self._global_search: GlobalSearch | None = None
        self._local_search:  LocalSearch  | None = None
        self._query_lock = asyncio.Lock()  # prevents concurrent _build_search_engines

    # ── Public API ────────────────────────────────────────────────────────────

    def initialize(self) -> None:
        """
        Called once at FastAPI startup (lifespan event).
        Creates the base working directory if it does not exist.
        Does NOT build search engines — those are built lazily on first query.
        """
        self._base_workdir.mkdir(parents=True, exist_ok=True)
        self._vector_store_dir.mkdir(parents=True, exist_ok=True)
        logger.info("GraphRAGService initialized | workdir=%s", self._base_workdir)

    async def run_indexing(self, doc_id: str, text: str) -> IndexingResult:
        """
        Run the full GraphRAG indexing pipeline for a single document.

        Steps:
          1. Create an isolated per-document working directory
          2. Write settings.yaml and the document text to input/
          3. Run `python -m graphrag index` as a subprocess
          4. Parse parquet output files into IndexingResult
          5. Clean up the working directory

        Returns IndexingResult with entities, relationships, and communities.
        Raises RuntimeError if indexing fails.

        NOTE: This function is CPU/IO-bound and can take 1–5 minutes depending
        on document length. It is designed to run inside Lambda (15-min timeout),
        NOT as part of a FastAPI request handler.
        """
        workdir = self._base_workdir / f"index_{doc_id}_{uuid.uuid4().hex[:8]}"

        try:
            logger.info("Starting GraphRAG indexing | doc_id=%s | workdir=%s", doc_id, workdir)

            # Step 1: Prepare isolated working directory
            self._prepare_workdir(workdir, text)

            # Step 2: Run indexing subprocess
            self._run_indexing_subprocess(workdir)

            # Step 3: Parse parquet output
            result = self._parse_output(doc_id, workdir)

            logger.info(
                "Indexing complete | doc_id=%s | entities=%d | relationships=%d | communities=%d",
                doc_id,
                len(result.entities),
                len(result.relationships),
                len(result.communities),
            )

            # Step 4: Invalidate cached search engines so next query picks up new data
            async with self._query_lock:
                self._global_search = None
                self._local_search  = None

            return result

        except Exception:
            logger.exception("GraphRAG indexing failed | doc_id=%s", doc_id)
            raise

        finally:
            # Always clean up per-document directory — parquet files are large
            if workdir.exists():
                shutil.rmtree(workdir, ignore_errors=True)
                logger.debug("Cleaned up workdir | path=%s", workdir)

    async def global_search(self, query: str) -> SearchResult:
        """
        Discover mode — reasons across ALL community summaries.

        Use for broad questions like 'what themes keep appearing in my saved content?'
        GraphRAG fans out parallel LLM calls across community batches, then reduces
        to a single answer. Slower than local_search but sees the whole graph.
        """
        engine = await self._get_global_search()
        try:
            raw = await engine.asearch(query)
            # raw.response is a string (after reduce step formats it as markdown)
            return SearchResult(
                response        = raw.response,
                entities_used   = [],  # global search doesn't return per-entity refs
                completion_time = raw.completion_time,
                llm_calls       = raw.llm_calls,
                prompt_tokens   = raw.prompt_tokens,
            )
        except Exception:
            logger.exception("GlobalSearch failed | query=%r", query)
            raise

    async def local_search(self, query: str, entity_names: list[str] | None = None) -> SearchResult:
        """
        Connect / Challenge mode — starts from specific entities, traverses nearby graph.

        Use for targeted questions like 'how does concept X relate to concept Y?'
        or contradiction detection. entity_names seeds the search; if None, GraphRAG
        infers the relevant entities from the query text.
        """
        engine = await self._get_local_search()
        try:
            raw = await engine.asearch(query)
            # Extract entity names that were actually used in the context
            entities_used: list[str] = []
            if hasattr(raw, "context_data") and raw.context_data:
                entities_df = raw.context_data.get("entities")
                if isinstance(entities_df, pd.DataFrame) and "entity" in entities_df.columns:
                    entities_used = entities_df["entity"].tolist()

            return SearchResult(
                response        = raw.response,
                entities_used   = entities_used,
                completion_time = raw.completion_time,
                llm_calls       = raw.llm_calls,
                prompt_tokens   = raw.prompt_tokens,
            )
        except Exception:
            logger.exception("LocalSearch failed | query=%r", query)
            raise

    # ── Private: working directory setup ─────────────────────────────────────

    def _prepare_workdir(self, workdir: Path, text: str) -> None:
        """
        Creates the per-document working directory structure:
          workdir/
            settings.yaml       ← GraphRAG config pointing to NVIDIA NIM
            input/
              document.txt      ← the document text to index
            cache/              ← GraphRAG writes LLM call cache here
            output/             ← parquet files written here after indexing
            logs/               ← GraphRAG progress logs
            prompts/            ← default prompts (GraphRAG init writes these)
        """
        (workdir / "input").mkdir(parents=True)
        (workdir / "cache").mkdir()
        (workdir / "output").mkdir()
        (workdir / "logs").mkdir()

        # Write settings.yaml from template
        settings_content = _SETTINGS_TEMPLATE.format(
            api_key   = self._settings.nvidia_api_key,
            model     = NVIDIA_NIM_MODEL,
            api_base  = NVIDIA_NIM_BASE_URL,
            embed_model = NVIDIA_EMBED_MODEL,
        )
        (workdir / "settings.yaml").write_text(settings_content, encoding="utf-8")

        # Write document as plain text — GraphRAG input type is 'text'
        (workdir / "input" / "document.txt").write_text(text, encoding="utf-8")

        # Generate default prompts (entity extraction, summarize, community report)
        # GraphRAG's init command writes these to prompts/ automatically.
        result = subprocess.run(
            ["python", "-m", "graphrag", "init", "--root", str(workdir)],
            capture_output=True, text=True, timeout=60,
        )
        # init may warn about existing files — that's fine, we only need prompts/
        if result.returncode != 0:
            # Non-fatal: prompts directory might already exist or init is informational
            logger.warning("graphrag init output: %s", result.stderr[:500])

    def _run_indexing_subprocess(self, workdir: Path) -> None:
        """
        Runs `python -m graphrag index --root <workdir>` as a subprocess.

        Why subprocess instead of importing graphrag.index directly:
          - GraphRAG's indexing pipeline is a CLI-first design; the Python API
            is internal and changes between minor versions without notice.
          - subprocess gives us clean stdout/stderr capture for CloudWatch logs.
          - A crash in the indexing pipeline cannot bring down the Lambda runtime.

        Timeout is set to 14 minutes (Lambda max is 15 min).
        """
        logger.info("Running GraphRAG indexing subprocess | workdir=%s", workdir)

        result = subprocess.run(
            ["python", "-m", "graphrag", "index", "--root", str(workdir)],
            capture_output=True,
            text=True,
            timeout=840,  # 14 minutes — Lambda timeout is 900s (15 min)
        )

        # Always log output for CloudWatch visibility
        if result.stdout:
            logger.info("GraphRAG stdout:\n%s", result.stdout[-3000:])  # last 3k chars
        if result.stderr:
            logger.warning("GraphRAG stderr:\n%s", result.stderr[-3000:])

        if result.returncode != 0:
            raise RuntimeError(
                f"GraphRAG indexing failed with exit code {result.returncode}. "
                f"stderr: {result.stderr[-1000:]}"
            )

    # ── Private: parquet parsing ──────────────────────────────────────────────

    def _parse_output(self, doc_id: str, workdir: Path) -> IndexingResult:
        """
        Reads GraphRAG's parquet output files and maps them to typed dataclasses.

        Expected output files (GraphRAG 0.3.6):
          output/artifacts/create_final_entities.parquet
          output/artifacts/create_final_nodes.parquet        ← needed for entity community mapping
          output/artifacts/create_final_relationships.parquet
          output/artifacts/create_final_community_reports.parquet
          output/artifacts/create_final_text_units.parquet   ← used by LocalSearch context
        """
        artifacts = workdir / "output" / "artifacts"

        if not artifacts.exists():
            raise RuntimeError(
                f"GraphRAG output directory not found at {artifacts}. "
                "Indexing may have failed silently."
            )

        # Read parquets — read_indexer_* are GraphRAG's own adapter functions
        # that normalize column names and return typed model objects.
        entity_df       = pd.read_parquet(artifacts / "create_final_entities.parquet")
        nodes_df        = pd.read_parquet(artifacts / "create_final_nodes.parquet")
        relationship_df = pd.read_parquet(artifacts / "create_final_relationships.parquet")
        community_df    = pd.read_parquet(artifacts / "create_final_community_reports.parquet")

        graphrag_entities      = read_indexer_entities(nodes_df, entity_df, COMMUNITY_LEVEL)
        graphrag_relationships = read_indexer_relationships(relationship_df)
        graphrag_communities   = read_indexer_reports(community_df, nodes_df, COMMUNITY_LEVEL)

        # Map GraphRAG model objects → our own dataclasses
        # We use our own types so the rest of the app has no graphrag import dependency.
        entities = [
            ExtractedEntity(
                id          = str(e.id),
                name        = e.title,
                type        = e.type or "UNKNOWN",
                description = e.description or "",
                community   = e.community_ids[0] if e.community_ids else None,
            )
            for e in graphrag_entities
        ]

        relationships = [
            ExtractedRelationship(
                id          = str(r.id),
                source      = r.source,
                target      = r.target,
                type        = r.description.split(" ")[0].upper() if r.description else "RELATES_TO",
                description = r.description or "",
                weight      = float(r.rank) if r.rank else 1.0,
            )
            for r in graphrag_relationships
        ]

        communities = [
            ExtractedCommunity(
                id      = str(c.id),
                title   = c.title,
                summary = c.summary,
                level   = COMMUNITY_LEVEL,
            )
            for c in graphrag_communities
        ]

        return IndexingResult(
            doc_id        = doc_id,
            entities      = entities,
            relationships = relationships,
            communities   = communities,
        )

    # ── Private: search engine construction ──────────────────────────────────

    async def _get_global_search(self) -> GlobalSearch:
        """
        Returns the cached GlobalSearch engine, building it if needed.
        Building is expensive (reads parquets, loads vector store), so we
        cache the result and invalidate it after each indexing run.
        """
        async with self._query_lock:
            if self._global_search is None:
                self._global_search = await asyncio.to_thread(self._build_global_search)
        return self._global_search

    async def _get_local_search(self) -> LocalSearch:
        """Same lazy-build pattern as _get_global_search."""
        async with self._query_lock:
            if self._local_search is None:
                self._local_search = await asyncio.to_thread(self._build_local_search)
        return self._local_search

    def _build_llm(self) -> ChatOpenAI:
        """
        Builds a ChatOpenAI client pointing at NVIDIA NIM.
        NIM exposes an OpenAI-compatible endpoint, so api_type stays OpenAI.
        """
        return ChatOpenAI(
            api_key        = self._settings.nvidia_api_key,
            api_base       = NVIDIA_NIM_BASE_URL,
            model          = NVIDIA_NIM_MODEL,
            api_type       = OpenaiApiType.OpenAI,
            max_retries    = 3,
            request_timeout = 120.0,
        )

    def _build_embedder(self) -> OpenAIEmbedding:
        """Builds an embedding client pointing at NVIDIA NIM's embedding endpoint."""
        return OpenAIEmbedding(
            api_key  = self._settings.nvidia_api_key,
            api_base = NVIDIA_NIM_BASE_URL,
            model    = NVIDIA_EMBED_MODEL,
            api_type = OpenaiApiType.OpenAI,
        )

    def _load_query_data(self) -> dict[str, Any]:
        """
        Loads all parquet files needed for query engines from the base workdir.
        These are the merged/cumulative artifacts from all indexing runs.

        NOTE: In this architecture, the Lambda writes GraphRAG output to S3 after
        each indexing run, and the query service loads from the local workdir that
        ECS has synced from S3. The sync step is handled in Lambda handler.py.
        """
        artifacts = self._base_workdir / "output" / "artifacts"

        if not artifacts.exists():
            raise RuntimeError(
                "No indexed documents found. Ingest and index at least one document before querying."
            )

        entity_df       = pd.read_parquet(artifacts / "create_final_entities.parquet")
        nodes_df        = pd.read_parquet(artifacts / "create_final_nodes.parquet")
        relationship_df = pd.read_parquet(artifacts / "create_final_relationships.parquet")
        community_df    = pd.read_parquet(artifacts / "create_final_community_reports.parquet")
        text_unit_df    = pd.read_parquet(artifacts / "create_final_text_units.parquet")

        entities      = read_indexer_entities(nodes_df, entity_df, COMMUNITY_LEVEL)
        relationships = read_indexer_relationships(relationship_df)
        communities   = read_indexer_reports(community_df, nodes_df, COMMUNITY_LEVEL)
        text_units    = read_indexer_text_units(text_unit_df)

        return {
            "entities":      entities,
            "relationships": relationships,
            "communities":   communities,
            "text_units":    text_units,
            "entity_df":     entity_df,   # needed for LanceDB vector store setup
        }

    def _build_global_search(self) -> GlobalSearch:
        """
        Builds the GlobalSearch engine.
        Called in a thread (via asyncio.to_thread) because pd.read_parquet is blocking.
        """
        logger.info("Building GlobalSearch engine")
        data = self._load_query_data()
        token_encoder = tiktoken.get_encoding("cl100k_base")

        context_builder = GlobalCommunityContext(
            community_reports = data["communities"],
            entities          = data["entities"],
            token_encoder     = token_encoder,
        )

        return GlobalSearch(
            llm             = self._build_llm(),
            context_builder = context_builder,
            token_encoder   = token_encoder,
            response_type   = "multiple paragraphs",
            # Allow some extra tokens for longer, richer Discover-mode answers
            max_data_tokens = 12000,
            map_llm_params  = {"max_tokens": 1000, "temperature": 0.0},
            reduce_llm_params = {"max_tokens": 2000, "temperature": 0.0},
        )

    def _build_local_search(self) -> LocalSearch:
        """
        Builds the LocalSearch engine with LanceDB vector store.
        Called in a thread (via asyncio.to_thread) because I/O is blocking.
        """
        logger.info("Building LocalSearch engine")
        data          = self._load_query_data()
        token_encoder = tiktoken.get_encoding("cl100k_base")
        embedder      = self._build_embedder()

        # LanceDB vector store — persisted to disk so it survives ECS restarts.
        # Entities are embedded by their description for semantic similarity lookup.
        vector_store = LanceDBVectorStore(collection_name="entity_descriptions")
        vector_store.connect(db_uri=str(self._vector_store_dir))

        # Only load embeddings into the store if it is empty (first run after new index)
        if vector_store.collection is None or vector_store.collection.count_rows() == 0:
            _load_entity_embeddings(vector_store, data["entity_df"])

        context_builder = LocalSearchMixedContext(
            entities                = data["entities"],
            entity_text_embeddings  = vector_store,
            text_embedder           = embedder,
            text_units              = data["text_units"],
            community_reports       = data["communities"],
            relationships           = data["relationships"],
            token_encoder           = token_encoder,
            embedding_vectorstore_key = EntityVectorStoreKey.ID,
        )

        return LocalSearch(
            llm             = self._build_llm(),
            context_builder = context_builder,
            token_encoder   = token_encoder,
            response_type   = "multiple paragraphs",
            llm_params      = {"max_tokens": 1500, "temperature": 0.0},
        )


# ── Helper ────────────────────────────────────────────────────────────────────

def _load_entity_embeddings(
    vector_store: LanceDBVectorStore,
    entity_df: pd.DataFrame,
) -> None:
    """
    Loads pre-computed description embeddings from the entity parquet into LanceDB.
    GraphRAG writes 'description_embedding' as a list column in the parquet.
    We push those vectors into LanceDB so LocalSearch can do similarity lookup.
    """
    if "description_embedding" not in entity_df.columns:
        logger.warning(
            "description_embedding column not found in entity parquet. "
            "LocalSearch semantic ranking will be degraded."
        )
        return

    from graphrag.vector_stores.base import VectorStoreDocument

    docs = [
        VectorStoreDocument(
            id        = str(row["id"]),
            text      = row.get("description", ""),
            vector    = row["description_embedding"],
            attributes = {"title": row.get("name", "")},
        )
        for _, row in entity_df.iterrows()
        if row.get("description_embedding") is not None
    ]

    vector_store.load_documents(docs)
    logger.info("Loaded %d entity embeddings into LanceDB", len(docs))


# ── Singleton export ──────────────────────────────────────────────────────────
# Import this in main.py lifespan and in every service/router that needs it.
# Never instantiate GraphRAGService directly outside this module.

graphrag_service = GraphRAGService()